import { useState } from "react"
import Section from "./Section"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./ui/card"
import { Badge } from "./ui/badge"
import { Button } from "./ui/button"
import { ExternalLink, ChevronRight, X } from "lucide-react"
import { FaGithub } from "react-icons/fa"
import { motion, AnimatePresence } from "framer-motion"

const projects = [
  {
    id: "trustnet",
    title: "TrustNet AI",
    subtitle: "AI-powered Fake Review Detection Platform",
    description: "An advanced natural language processing system that identifies and flags inauthentic product reviews across e-commerce platforms using sentiment analysis and Large Language Models.",
    problem: "E-commerce platforms are plagued by fake reviews, making it difficult for consumers to make informed decisions and damaging trust in online marketplaces.",
    solution: "Developed an AI system that analyzes linguistic patterns, sentiment consistency, and metadata to classify reviews as genuine or fake with high accuracy.",
    architecture: "Microservices architecture with a React frontend, Python FastAPI backend, and PostgreSQL database. NLP processing is handled by a dedicated ML microservice.",
    techStack: ["Python", "FastAPI", "React", "Hugging Face", "Scikit-learn", "PostgreSQL"],
    features: ["Real-time review analysis", "Batch processing API", "Trust score dashboard", "Browser extension integration"],
    challenges: "Handling the nuance of subtle fake reviews generated by LLMs required fine-tuning our own models rather than relying on standard sentiment analysis.",
    future: "Integrating real-time seller verification and expanding to social media sentiment tracking.",
    github: "#",
    demo: "#"
  },
  {
    id: "aris",
    title: "ARIS",
    subtitle: "AI Resume Intelligence System",
    description: "An intelligent resume analyzer that predicts ATS scores, provides actionable feedback, and matches candidates to suitable job descriptions based on semantic similarity.",
    problem: "Job seekers often struggle to optimize their resumes for Applicant Tracking Systems (ATS), resulting in qualified candidates being automatically rejected.",
    solution: "Built a platform that simulates ATS parsing and scoring, offering precise recommendations to improve resume visibility and formatting.",
    architecture: "Serverless architecture using AWS Lambda for resume parsing (PDF/Word), NLP embeddings for matching, and a modern React frontend for the user dashboard.",
    techStack: ["React", "Python", "AWS Lambda", "NLTK", "Spacy", "OpenAI API"],
    features: ["ATS score prediction", "Keyword gap analysis", "Job description matching", "Formatting feedback"],
    challenges: "Parsing complex PDF layouts reliably required developing a custom hybrid parsing engine combining OCR and structural analysis.",
    future: "Adding automated cover letter generation and interview preparation based on the matched job description.",
    github: "#",
    demo: "#"
  },
  {
    id: "salary",
    title: "Employee Salary Standardization",
    description: "A machine learning pipeline that predicts fair salaries and identifies pay disparities using regression, feature engineering, and robust data preprocessing techniques.",
    problem: "Inconsistent salary structures within large organizations can lead to pay inequity and employee dissatisfaction.",
    solution: "Created a predictive model that establishes baseline fair compensation based on experience, location, role, and performance metrics.",
    architecture: "Jupyter Notebook based data pipeline integrated into a Flask web application for HR professionals to query salary ranges.",
    techStack: ["Python", "Pandas", "Scikit-learn", "Flask", "Matplotlib"],
    features: ["Salary prediction engine", "Disparity identification", "Market rate comparison", "Interactive visualizations"],
    challenges: "Handling missing data and categorical variables with high cardinality without introducing bias into the model.",
    future: "Incorporating real-time market data from external APIs to keep baseline predictions current.",
    github: "#",
    demo: "#"
  },
  {
    id: "student",
    title: "Student Performance Analytics System",
    description: "A comprehensive data warehousing solution with predictive analytics dashboards to monitor and forecast student academic performance.",
    problem: "Educational institutions lack actionable insights from their vast amounts of student data, making early intervention difficult.",
    solution: "Designed a centralized data warehouse and Power BI dashboards that highlight at-risk students and trends in academic performance.",
    architecture: "ETL pipelines moving data from SIS to a SQL Server Data Warehouse, with Power BI connected via DirectQuery for real-time reporting.",
    techStack: ["SQL Server", "Power BI", "Python", "SSIS", "Data Mining"],
    features: ["At-risk student prediction", "Departmental performance dashboards", "Historical trend analysis", "Automated reporting"],
    challenges: "Integrating siloed data sources with different schema definitions into a unified dimensional model.",
    future: "Adding NLP capabilities to analyze student feedback and correlate it with performance metrics.",
    github: "#",
    demo: "#"
  },
  {
    id: "iot",
    title: "IoT-Based Self Defense System",
    description: "A wearable safety device utilizing Arduino, GSM/GPS modules, and cloud integration to provide emergency alerts and location tracking for women's safety.",
    problem: "In emergency situations, standard mobile phones can be difficult to access or operate quickly to call for help.",
    solution: "Engineered a discreet wearable device that triggers multiple safety protocols (GPS tracking, SMS alerts, loud alarm) with a single concealed action.",
    architecture: "Arduino-based hardware communicating via GSM/GPS shields, sending telemetry to a cloud-based alert distribution system.",
    techStack: ["Arduino", "C++", "GSM/GPS", "IoT Cloud", "Sensors"],
    features: ["One-touch activation", "Real-time GPS tracking", "Automated SMS to emergency contacts", "Local high-decibel alarm"],
    challenges: "Miniaturizing the hardware components and optimizing battery life while maintaining reliable GSM connection.",
    future: "Developing a companion mobile app for configuring emergency contacts and analyzing route safety.",
    github: "#",
    demo: "#"
  }
]

export default function Projects() {
  const [selectedProject, setSelectedProject] = useState<typeof projects[0] | null>(null)

  return (
    <Section id="projects" title="Featured Projects" subtitle="A selection of my best work in AI, Machine Learning, and Software Engineering.">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {projects.map((project, index) => (
          <motion.div
            key={project.id}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-50px" }}
            transition={{ duration: 0.4, delay: index * 0.1 }}
          >
            <Card className="h-full flex flex-col border-border/50 shadow-sm hover:shadow-md transition-all duration-300 hover:-translate-y-1 cursor-pointer overflow-hidden group"
                  onClick={() => setSelectedProject(project)}>
              <div className="h-48 w-full overflow-hidden relative border-b border-border/50">
                <div 
                  className="absolute inset-0 bg-cover bg-center group-hover:scale-105 transition-transform duration-500 opacity-60"
                  style={{ backgroundImage: 'url(/images/project_bg.png)' }}
                />
                <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-background/80 to-background/20 backdrop-blur-[2px]">
                   <span className="text-foreground font-heading font-bold text-xl tracking-wide shadow-sm drop-shadow-sm">{project.title}</span>
                </div>
              </div>
              <CardHeader>
                <CardTitle className="text-xl">{project.title}</CardTitle>
                <CardDescription className="line-clamp-2 mt-2">{project.description}</CardDescription>
              </CardHeader>
              <CardContent className="flex-grow">
                <div className="flex flex-wrap gap-2 mt-auto">
                  {project.techStack.slice(0, 3).map(tech => (
                    <Badge key={tech} variant="secondary" className="text-xs font-normal bg-secondary/50">{tech}</Badge>
                  ))}
                  {project.techStack.length > 3 && (
                    <Badge variant="secondary" className="text-xs font-normal bg-secondary/50">+{project.techStack.length - 3}</Badge>
                  )}
                </div>
              </CardContent>
              <CardFooter className="pt-0 border-t border-border/10 mt-4">
                <div className="flex items-center text-sm font-medium text-primary mt-4 group-hover:underline">
                  View Case Study <ChevronRight className="ml-1 h-4 w-4" />
                </div>
              </CardFooter>
            </Card>
          </motion.div>
        ))}
      </div>

      {/* Project Modal */}
      <AnimatePresence>
        {selectedProject && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 overflow-hidden">
            <motion.div 
              initial={{ opacity: 0 }} 
              animate={{ opacity: 1 }} 
              exit={{ opacity: 0 }} 
              onClick={() => setSelectedProject(null)}
              className="absolute inset-0 bg-background/80 backdrop-blur-sm"
            />
            
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              transition={{ type: "spring", damping: 25, stiffness: 300 }}
              className="relative w-full max-w-4xl max-h-[90vh] bg-card rounded-xl shadow-2xl overflow-y-auto border border-border"
            >
              <div className="sticky top-0 z-10 flex items-center justify-between px-6 py-4 border-b bg-card/95 backdrop-blur supports-[backdrop-filter]:bg-card/80">
                <h2 className="text-2xl font-bold font-heading">{selectedProject.title}</h2>
                <Button variant="ghost" size="icon" onClick={() => setSelectedProject(null)}>
                  <X className="h-5 w-5" />
                </Button>
              </div>

              <div className="p-6 sm:p-8 space-y-8">
                {/* Hero / Overview */}
                <div>
                  <h3 className="text-lg font-medium text-muted-foreground mb-2">{selectedProject.subtitle || "Overview"}</h3>
                  <p className="text-foreground leading-relaxed">{selectedProject.description}</p>
                </div>

                <div className="flex flex-wrap gap-2">
                  {selectedProject.techStack.map(tech => (
                    <Badge key={tech} variant="outline" className="bg-primary/5">{tech}</Badge>
                  ))}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-4 border-t">
                  {/* Problem & Solution */}
                  <div className="space-y-6">
                    <div>
                      <h4 className="text-lg font-semibold flex items-center mb-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-destructive mr-2" />
                        The Problem
                      </h4>
                      <p className="text-muted-foreground text-sm leading-relaxed">{selectedProject.problem}</p>
                    </div>
                    <div>
                      <h4 className="text-lg font-semibold flex items-center mb-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-primary mr-2" />
                        The Solution
                      </h4>
                      <p className="text-muted-foreground text-sm leading-relaxed">{selectedProject.solution}</p>
                    </div>
                  </div>

                  {/* Architecture & Features */}
                  <div className="space-y-6">
                     <div>
                      <h4 className="text-lg font-semibold mb-2">Architecture</h4>
                      <p className="text-muted-foreground text-sm leading-relaxed">{selectedProject.architecture}</p>
                    </div>
                    <div>
                      <h4 className="text-lg font-semibold mb-2">Key Features</h4>
                      <ul className="list-disc list-inside text-muted-foreground text-sm space-y-1">
                        {selectedProject.features.map(feature => (
                          <li key={feature}>{feature}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t">
                  <h4 className="text-lg font-semibold mb-2">Challenges & Future</h4>
                  <p className="text-muted-foreground text-sm leading-relaxed mb-4">
                    <strong>Challenges:</strong> {selectedProject.challenges}
                  </p>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    <strong>Future Improvements:</strong> {selectedProject.future}
                  </p>
                </div>

                <div className="flex flex-wrap gap-4 pt-6 mt-6 border-t">
                  <Button asChild>
                    <a href={selectedProject.github} target="_blank" rel="noreferrer">
                      <FaGithub className="mr-2 h-4 w-4" /> View Source
                    </a>
                  </Button>
                  <Button variant="outline" asChild>
                    <a href={selectedProject.demo} target="_blank" rel="noreferrer">
                      <ExternalLink className="mr-2 h-4 w-4" /> Live Demo
                    </a>
                  </Button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </Section>
  )
}
